/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/lessons/{lesson_id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get attendance for a lesson */
        get: operations["get_attendance_lessons__lesson_id__attendance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/{attendance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update attendance status */
        patch: operations["patch_attendance_attendance__attendance_id__patch"];
        trace?: never;
    };
    "/attendance/{attendance_id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move attendance record to a different lesson */
        post: operations["move_attendance_record_attendance__attendance_id__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current authenticated user */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user (admin only) */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/export/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export enrolled students */
        get: operations["export_students_subjects__subject_id__export_students_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/export/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export attendance matrix */
        get: operations["export_attendance_subjects__subject_id__export_attendance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{semester_id}/schedule/{entry_id}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get lessons for a schedule entry */
        get: operations["list_lessons_semesters__semester_id__schedule__entry_id__lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a lesson */
        patch: operations["patch_lesson_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/semesters/{semester_id}/week/{week_number}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all lessons for a week with attendance summaries */
        get: operations["get_week_semesters__semester_id__week__week_number__lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_scans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/isics/{isic_identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Isic Info */
        patch: operations["update_isic_info_isics__isic_identifier__patch"];
        trace?: never;
    };
    "/semesters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all semesters */
        get: operations["list_semesters_semesters_get"];
        put?: never;
        /** Create a semester */
        post: operations["create_semester_endpoint_semesters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{semester_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a semester */
        delete: operations["delete_semester_endpoint_semesters__semester_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List enrolled students */
        get: operations["list_students_subjects__subject_id__students_get"];
        put?: never;
        /** Enroll a student */
        post: operations["enroll_student_endpoint_subjects__subject_id__students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/students/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import students from CSV */
        post: operations["import_students_endpoint_subjects__subject_id__students_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/students/{enrollment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove student enrollment */
        delete: operations["delete_enrollment_endpoint_subjects__subject_id__students__enrollment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subjects */
        get: operations["list_subjects_subjects_get"];
        put?: never;
        /** Create a subject */
        post: operations["create_subject_endpoint_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a subject */
        put: operations["update_subject_endpoint_subjects__subject_id__put"];
        post?: never;
        /** Delete a subject */
        delete: operations["delete_subject_endpoint_subjects__subject_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}/schedule-entries/{entry_id}/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get schedule entry attendance overview */
        get: operations["get_overview_subjects__subject_id__schedule_entries__entry_id__overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{semester_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get schedule for a semester */
        get: operations["get_schedule_semesters__semester_id__schedule_get"];
        put?: never;
        /** Create a schedule entry */
        post: operations["create_schedule_semesters__semester_id__schedule_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{semester_id}/schedule/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a schedule entry */
        delete: operations["delete_schedule_semesters__semester_id__schedule__entry_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{semester_id}/weeks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get weeks with notes for a semester */
        get: operations["get_weeks_semesters__semester_id__weeks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/semesters/{semester_id}/weeks/{week_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a week note */
        patch: operations["update_week_note_semesters__semester_id__weeks__week_number__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttendanceLessonInfo */
        AttendanceLessonInfo: {
            /** Id */
            id: number;
            /** Subject Name */
            subject_name: string;
            /** Subject Color */
            subject_color: string;
            /** Lesson Type */
            lesson_type: string;
            /** Week Number */
            week_number: number;
            /** Date */
            date: string;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /** Room */
            room: string | null;
            /** Day Of Week */
            day_of_week: number;
            /** Recurrence */
            recurrence: string;
        };
        /** AttendanceMoveRequest */
        AttendanceMoveRequest: {
            /** Target Lesson Id */
            target_lesson_id: number;
        };
        /** AttendanceMoveResponse */
        AttendanceMoveResponse: {
            /** Attendance Id */
            attendance_id: number;
            /** Lesson Id */
            lesson_id: number;
            /** Status */
            status: string;
        };
        /** AttendanceResponse */
        AttendanceResponse: {
            lesson: components["schemas"]["AttendanceLessonInfo"];
            /** Students */
            students: components["schemas"]["AttendanceStudentEntry"][];
            summary: components["schemas"]["AttendanceSummary"];
        };
        /** AttendanceStudentEntry */
        AttendanceStudentEntry: {
            /** Attendance Id */
            attendance_id: number;
            /** Isic Identifier */
            isic_identifier: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Status */
            status: string;
            /** Marked By */
            marked_by: string;
            /** Scan Timestamp */
            scan_timestamp: string | null;
        };
        /** AttendanceSummary */
        AttendanceSummary: {
            /** Total */
            total: number;
            /** Pritomny */
            pritomny: number;
            /** Nepritomny */
            nepritomny: number;
            /** Nahrada */
            nahrada: number;
            /** Ospravedlneny */
            ospravedlneny: number;
        };
        /** AttendanceUpdateRequest */
        AttendanceUpdateRequest: {
            /** Status */
            status: string;
        };
        /** AttendanceUpdateResponse */
        AttendanceUpdateResponse: {
            /** Attendance Id */
            attendance_id: number;
            /** Status */
            status: string;
            /** Marked By */
            marked_by: string;
        };
        /** Body_import_students_endpoint_subjects__subject_id__students_import_post */
        Body_import_students_endpoint_subjects__subject_id__students_import_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** EnrollStudentRequest */
        EnrollStudentRequest: {
            /** Isic Identifier */
            isic_identifier: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
        };
        /** EnrollmentResponse */
        EnrollmentResponse: {
            /** Enrollment Id */
            enrollment_id: number;
            /** Isic Id */
            isic_id: number;
            /** Isic Identifier */
            isic_identifier: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Enrolled At */
            enrolled_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @description Health status
             */
            status: string;
        };
        /** ISICResponse */
        ISICResponse: {
            /**
             * Id
             * @description ISIC ID
             */
            id: number;
            /**
             * Isic Identifier
             * @description ISIC identifier
             */
            isic_identifier: string;
            /**
             * First Name
             * @description First name
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Last name
             */
            last_name?: string | null;
            /**
             * Created At
             * @description ISIC creation timestamp in ISO format
             */
            created_at: string;
        };
        /** ISICUpdateRequest */
        ISICUpdateRequest: {
            /**
             * First Name
             * @description First name
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Last name
             */
            last_name?: string | null;
        };
        /** ImportError_ */
        ImportError_: {
            /** Row */
            row: number;
            /** Reason */
            reason: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Imported */
            imported: number;
            /** Skipped */
            skipped: number;
            /** Errors */
            errors: components["schemas"]["ImportError_"][];
        };
        /** LessonResponse */
        LessonResponse: {
            /** Id */
            id: number;
            /** Week Number */
            week_number: number;
            /** Date */
            date: string;
            /** Cancelled */
            cancelled: boolean;
        };
        /** LessonUpdateRequest */
        LessonUpdateRequest: {
            /** Cancelled */
            cancelled?: boolean | null;
        };
        /** OverviewResponse */
        OverviewResponse: {
            schedule_entry: components["schemas"]["OverviewScheduleEntry"];
            /** Weeks */
            weeks: components["schemas"]["OverviewWeek"][];
            /** Students */
            students: components["schemas"]["OverviewStudent"][];
        };
        /** OverviewScheduleEntry */
        OverviewScheduleEntry: {
            /** Id */
            id: number;
            /** Subject Name */
            subject_name: string;
            /** Lesson Type */
            lesson_type: string;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /** Day Of Week */
            day_of_week: number;
            /** Subject Color */
            subject_color: string;
            /** Recurrence */
            recurrence: string;
        };
        /** OverviewStudent */
        OverviewStudent: {
            /** Isic Identifier */
            isic_identifier: string;
            /** First Name */
            first_name: string | null;
            /** Last Name */
            last_name: string | null;
            /** Weeks */
            weeks: components["schemas"]["OverviewStudentWeek"][];
        };
        /** OverviewStudentWeek */
        OverviewStudentWeek: {
            /** Week Number */
            week_number: number;
            /** Attendance Id */
            attendance_id: number | null;
            /** Status */
            status: string | null;
        };
        /** OverviewWeek */
        OverviewWeek: {
            /** Week Number */
            week_number: number;
            /** Date Range */
            date_range: string;
            /** Lesson Id */
            lesson_id: number | null;
            /** Is Current */
            is_current: boolean;
        };
        /** RegisterRequest */
        RegisterRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /**
             * Role
             * @default teacher
             */
            role: string;
        };
        /**
         * ScanResponse
         * @example {
         *       "created_at": "2024-01-01T12:00:00+00:00",
         *       "id": 1,
         *       "isic_id": 1,
         *       "isic_identifier": "ISIC123456",
         *       "timestamp": "2024-01-01T12:00:00+00:00"
         *     }
         */
        ScanResponse: {
            /**
             * Id
             * @description Scan ID
             */
            id: number;
            /**
             * Isic Id
             * @description ISIC ID
             */
            isic_id: number;
            /**
             * Isic Identifier
             * @description ISIC identifier
             */
            isic_identifier: string;
            /**
             * First Name
             * @description First name
             */
            first_name?: string | null;
            /**
             * Last Name
             * @description Last name
             */
            last_name?: string | null;
            /**
             * Timestamp
             * @description Scan timestamp in ISO format
             */
            timestamp: string;
            /**
             * Created At
             * @description Scan creation timestamp in ISO format
             */
            created_at: string;
        };
        /** ScheduleEntryCreate */
        ScheduleEntryCreate: {
            /** Subject Id */
            subject_id: number;
            /** Day Of Week */
            day_of_week: number;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /** Room */
            room?: string | null;
            /** Lesson Type */
            lesson_type: string;
            /**
             * Is One Time
             * @default false
             */
            is_one_time: boolean;
            /**
             * Recurrence Interval
             * @default 1
             */
            recurrence_interval: number;
            /** End Date */
            end_date?: string | null;
        };
        /** ScheduleEntryResponse */
        ScheduleEntryResponse: {
            /** Id */
            id: number;
            /** Subject Id */
            subject_id: number;
            /** Subject Name */
            subject_name: string;
            /** Subject Code */
            subject_code: string;
            /** Subject Color */
            subject_color: string;
            /** Day Of Week */
            day_of_week: number;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /** Room */
            room: string | null;
            /** Lesson Type */
            lesson_type: string;
            /** Is One Time */
            is_one_time: boolean;
            /** Recurrence Interval */
            recurrence_interval: number;
            /** End Date */
            end_date: string | null;
        };
        /** SemesterCreate */
        SemesterCreate: {
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Total Weeks
             * @default 13
             */
            total_weeks: number;
        };
        /** SemesterResponse */
        SemesterResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /** Total Weeks */
            total_weeks: number;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** Name */
            name: string;
            /** Code */
            code: string;
            /**
             * Color
             * @default #4CAF50
             */
            color: string;
        };
        /** SubjectResponse */
        SubjectResponse: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Code */
            code: string;
            /** Color */
            color: string;
            /** Teacher Name */
            teacher_name: string;
        };
        /** SubjectUpdate */
        SubjectUpdate: {
            /** Name */
            name?: string | null;
            /** Code */
            code?: string | null;
            /** Color */
            color?: string | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekLessonAttendanceSummary */
        WeekLessonAttendanceSummary: {
            /** Total */
            total: number;
            /** Pritomny */
            pritomny: number;
            /** Nepritomny */
            nepritomny: number;
            /** Nahrada */
            nahrada: number;
        };
        /** WeekLessonResponse */
        WeekLessonResponse: {
            /** Lesson Id */
            lesson_id: number;
            /** Schedule Entry Id */
            schedule_entry_id: number;
            /** Subject Name */
            subject_name: string;
            /** Lesson Type */
            lesson_type: string;
            /** Day Of Week */
            day_of_week: number;
            /** Start Time */
            start_time: string;
            /** End Time */
            end_time: string;
            /** Room */
            room: string | null;
            attendance_summary: components["schemas"]["WeekLessonAttendanceSummary"];
        };
        /** WeekNoteUpdate */
        WeekNoteUpdate: {
            /** Note */
            note: string;
        };
        /** WeekResponse */
        WeekResponse: {
            /** Week Number */
            week_number: number;
            /** Note */
            note: string;
            /** Date Range */
            date_range: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_attendance_lessons__lesson_id__attendance_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceResponse"];
                };
            };
            /** @description Not your subject */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_attendance_attendance__attendance_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attendance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceUpdateResponse"];
                };
            };
            /** @description Attendance record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_attendance_record_attendance__attendance_id__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attendance_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceMoveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceMoveResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not your subject */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Attendance record not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Invalid or expired token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Email already registered */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_students_subjects__subject_id__export_students_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_attendance_subjects__subject_id__export_attendance_get: {
        parameters: {
            query: {
                semester_id: number;
                format?: string;
            };
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_lessons_semesters__semester_id__schedule__entry_id__lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_lesson_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Not your subject */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_week_semesters__semester_id__week__week_number__lessons_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
                week_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekLessonResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_scans_scans_get: {
        parameters: {
            query: {
                /** @description Maximum number of scans to return */
                limit: number;
                /** @description Number of scans to skip */
                offset: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_isic_info_isics__isic_identifier__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isic_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ISICUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ISICResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_semesters_semesters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemesterResponse"][];
                };
            };
        };
    };
    create_semester_endpoint_semesters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SemesterCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SemesterResponse"];
                };
            };
            /** @description Semester name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_semester_endpoint_semesters__semester_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_subjects__subject_id__students_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_student_endpoint_subjects__subject_id__students_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollStudentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description Student already enrolled */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_students_endpoint_subjects__subject_id__students_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_students_endpoint_subjects__subject_id__students_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_enrollment_endpoint_subjects__subject_id__students__enrollment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
                enrollment_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Enrollment not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_subjects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"][];
                };
            };
        };
    };
    create_subject_endpoint_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            /** @description Subject code already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_endpoint_subjects__subject_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectResponse"];
                };
            };
            /** @description Not your subject */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_endpoint_subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Not your subject */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_overview_subjects__subject_id__schedule_entries__entry_id__overview_get: {
        parameters: {
            query: {
                semester_id: number;
            };
            header?: never;
            path: {
                subject_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Not your subject */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_semesters__semester_id__schedule_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryResponse"][];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_schedule_semesters__semester_id__schedule_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleEntryResponse"];
                };
            };
            /** @description Semester or subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_schedule_semesters__semester_id__schedule__entry_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Schedule entry not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weeks_semesters__semester_id__weeks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekResponse"][];
                };
            };
            /** @description Semester not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_week_note_semesters__semester_id__weeks__week_number__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                semester_id: number;
                week_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeekNoteUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeekResponse"];
                };
            };
            /** @description Week not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
